# Generated by Django 5.0.6 on 2024-06-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
