# Generated by Django 5.0.6 on 2024-06-14 00:28

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_leccion_lesson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='course description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Medium', 'Medium'), ('Advanced', 'advanced')], default='Initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='miniature',
            field=models.ImageField(default='miniatures/default.jpg', upload_to=courses.models.generar_nombre_miniatura, verbose_name='miniature'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='course name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='num_lessons',
            field=models.IntegerField(default=0, editable=False, verbose_name='number of lessons'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='course',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leccions', to='courses.course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='miniature',
            field=models.ImageField(default='miniatures/default.jpg', upload_to=courses.models.generar_nombre_miniatura, verbose_name='miniature'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.generar_nombre_video, verbose_name='video'),
        ),
    ]
