# Generated by Django 5.0.6 on 2024-06-14 02:23

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], default='Initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='miniature',
            field=models.ImageField(default='miniatures/default.jpg', upload_to=courses.models.generar_nombre_miniatura, verbose_name='Miniature'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name of Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='num_lessons',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of Lessons'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='course',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lessons', to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='miniature',
            field=models.ImageField(default='miniatures/default.jpg', upload_to=courses.models.generar_nombre_miniatura, verbose_name='Miniature'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.generar_nombre_video, verbose_name='Video'),
        ),
    ]
