# Generated by Django 5.0.6 on 2024-06-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_options_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], default='Initial', max_length=20, verbose_name='Course Level'),
        ),
    ]
