# Generated by Django 5.0.6 on 2024-06-17 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='num_lessons',
            new_name='num_modules',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Module', max_length=200, unique=True, verbose_name='Name of Module')),
                ('description', models.CharField(max_length=10000, verbose_name='Module Description')),
                ('num_lessons', models.IntegerField(default=0, editable=False, verbose_name='Number of Lessons')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modules', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modules', to='courses.module', verbose_name='Module'),
        ),
    ]
