# Generated by Django 5.0.6 on 2024-06-17 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_num_lessons_course_num_modules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modules', to='courses.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name of Module'),
        ),
    ]
