# Generated by Django 5.0.6 on 2024-06-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lesson_module_alter_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_modules',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of Modules'),
        ),
    ]
