# Generated by Django 5.0.6 on 2024-06-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_level'),
        ('exams', '0002_alter_exam_options_alter_option_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course', verbose_name='Course'),
        ),
    ]
