# Generated by Django 5.0.6 on 2024-06-19 06:27

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_avatar_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to=users.models.generar_nombre, verbose_name='Avatar'),
        ),
    ]
