# Generated by Django 5.0.6 on 2024-06-13 23:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
        ('courses', '0003_rename_leccion_lesson_and_more'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examrealizado',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examrealizado',
            name='user',
        ),
        migrations.CreateModel(
            name='ExamRealized',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('examrealized', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.examrealized')),
            ],
        ),
        migrations.DeleteModel(
            name='Certificado',
        ),
        migrations.DeleteModel(
            name='ExamRealizado',
        ),
    ]
