# Generated by Django 5.0.6 on 2024-06-14 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificados', '0001_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examrealized',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='Exam'),
        ),
        migrations.AddField(
            model_name='examrealized',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='examrealized',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.examrealized', verbose_name='Exam Realized'),
        ),
    ]
