# Generated by Django 5.0.6 on 2024-06-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='certificates/', verbose_name='PDF'),
        ),
    ]
